In [1]:
import pickle
import numpy as np
import cv2

objects = []
with (open("full_CNN_train.p", "rb")) as openfile:
    while True:
        try:
            objects.append(pickle.load(openfile))
        except EOFError:
            break

In [14]:
objects=np.squeeze(np.array(objects),0)

In [15]:
objects.shape

(12764, 80, 160, 3)

In [27]:
cv2.imshow('gggg', objects[8000])
cv2.waitKey(0)

-1

In [11]:
object_label = []
with (open("full_CNN_labels.p", "rb")) as openfile:
    while True:
        try:
            object_label.append(pickle.load(openfile))
        except EOFError:
            break

In [12]:
object_label

[[array([[[0],
          [0],
          [0],
          ...,
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          ...,
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          ...,
          [0],
          [0],
          [0]],
  
         ...,
  
         [[0],
          [0],
          [0],
          ...,
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          ...,
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          ...,
          [0],
          [0],
          [0]]], dtype=uint8),
  array([[[0],
          [0],
          [0],
          ...,
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          ...,
          [0],
          [0],
          [0]],
  
         [[0],
          [0],
          [0],
          ...,
          [0],
          [0],
         

In [53]:
with (open("label.p", "rb")) as openfile:
    objects_label=pickle.load(openfile)

In [54]:
objects_label

[array([[[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],
 
        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],
 
        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],
 
        ...,
 
        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],
 
        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],
 
        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]]]),
 array([[[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],
 
        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],
 
        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],
 
        ...,
 
        [[0],
         [0],
         [0],
         ...,
     

In [61]:
objects_label[0].shape

(80, 160, 1)

In [62]:
type(objects_label)

list

In [63]:
len(objects_label)

104

In [39]:
objects_label=np.array(objects_label)

In [37]:
objects_label.shape

(12764, 80, 160, 1)

In [31]:
cv2.imshow('gggg', objects_label[500])
cv2.waitKey(0)

-1

In [8]:
objects_label[590]

array([[[ 0],
        [ 0],
        [ 0],
        ...,
        [ 0],
        [ 0],
        [ 0]],

       [[ 0],
        [ 0],
        [ 0],
        ...,
        [ 0],
        [ 0],
        [ 0]],

       [[ 0],
        [ 0],
        [ 0],
        ...,
        [ 0],
        [ 0],
        [ 0]],

       ...,

       [[ 0],
        [ 0],
        [ 0],
        ...,
        [ 0],
        [ 0],
        [ 0]],

       [[ 0],
        [ 0],
        [ 0],
        ...,
        [ 0],
        [ 0],
        [ 0]],

       [[ 0],
        [ 0],
        [ 0],
        ...,
        [12],
        [ 0],
        [ 0]]], dtype=uint8)

In [17]:
objects_label=objects_label[:,:,:,0:1]

In [31]:
 objects_label=np.array(objects_label).tolist()

In [47]:
objects_label=list(objects_label)

In [52]:
file = open('label.p', 'wb')

# Pickle dictionary using protocol 0.
pickle.dump(objects_label, file)
file.close()

In [72]:
#img=objects_label[5]
rows,cols = img.shape
for i in range(rows):
        x = []
        for j in range(cols):
            #k = gray[i,j]
            #print(k)
            x.append(img[i,j])
        print(x)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [70]:
img=np.squeeze(img,2)

In [71]:
img.shape

(80, 160)

In [73]:
img

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [5]:
objects[0].shape

AttributeError: 'list' object has no attribute 'shape'

In [7]:
np.array(objects).shape

(1, 12764, 80, 160, 3)

In [3]:
cv2.imshow('gggg', np.array(objects)[0,0])
cv2.waitKey(0)

-1